BEGIN;
CREATE TEMP TABLE _lote (id int, novo text) ON COMMIT DROP;
INSERT INTO _lote (id, novo) VALUES
  -- COMMODITY (traducao fiel)
  (4073, $N$Varinha de Acompanhamento$N$),
  (4074, $N$Varinha de Glifos de Ar$N$),
  (2409, $N$Varinha de Atadura$N$),
  (4077, $N$Varinha de Cerdas$N$),
  (4078, $N$Varinha de Teias de Aranha$N$),
  (2411, $N$Varinha de Regência$N$),
  (4079, $N$Varinha de Detecção de Profundidade$N$),
  (4080, $N$Varinha de Direção$N$),
  (4081, $N$Varinha de Afogamento$N$),
  (4082, $N$Varinha de Elocução$N$),
  (2413, $N$Varinha de Detecção de Inimigos$N$),
  (2415, $N$Varinha de Enredar$N$),
  (4085, $N$Varinha de Erudição$N$),
  (4086, $N$Varinha de Extinção$N$),
  (2416, $N$Varinha do Medo$N$),
  (4089, $N$Varinha de Fermentação$N$),
  (2418, $N$Varinha de Bolas de Fogo$N$),
  (4092, $N$Varinha de Controle de Chamas$N$),
  (4093, $N$Varinha das Risadinhas$N$),
  (4094, $N$Varinha de Orientação$N$),
  (4095, $N$Varinha do Tormento$N$),
  (4096, $N$Varinha de Ignição$N$),
  (2420, $N$Varinha de Raios Relâmpago$N$),
  (2422, $N$Varinha de Detecção de Magia$N$),
  (4101, $N$Varinha de Míssil Mágico$N$),
  (2424, $N$Varinha de Mísseis Mágicos$N$),
  (2428, $N$Varinha de Paralisia$N$),
  (4105, $N$Varinha de Destruição Vegetal$N$),
  (2430, $N$Varinha de Metamorfose$N$),
  (2432, $N$Varinha de Pirotecnia$N$),
  (4108, $N$Varinha de Alívio de Fardos$N$),
  (4110, $N$Varinha de Revelação$N$),
  (2434, $N$Varinha das Carrancas$N$),
  (2435, $N$Varinha dos Segredos$N$),
  (2437, $N$Varinha dos Sorrisos$N$),
  (4113, $N$Varinha das Lágrimas$N$),
  (4120, $N$Varinha de Localização de Tesouro$N$),
  (4121, $N$Varinha de Vapores$N$),
  (2438, $N$Varinha de Glóbulos Viscosos$N$),
  (2439, $N$Varinha de Teia$N$),
  (4124, $N$Varinha de Janelas$N$),
  (2441, $N$Varinha do Inverno$N$),
  (2442, $N$Varinha da Maravilha$N$),
  (4114, $N$Varinha do Escriba$N$),
  (4115, $N$Varinha do Cronometrista$N$),
  (1977, $N$Bastão de Absorção$N$),
  (1979, $N$Bastão de Vigilância$N$),
  (3686, $N$Bastão de Curvar Lâminas$N$),
  (3687, $N$Bastão de Bolhas$N$),
  (3688, $N$Bastão de Transporte$N$),
  (3689, $N$Bastão de Deflexão$N$),
  (3690, $N$Bastão de Entropia$N$),
  (3691, $N$Bastão do Vigor Medonho$N$),
  (3693, $N$Bastão de Sincelos$N$),
  (1982, $N$Bastão do Poder Senhorial$N$),
  (3696, $N$Bastão de Reforma$N$),
  (3697, $N$Bastão do Saqueador$N$),
  (1984, $N$Bastão de Ressurreição$N$),
  (1986, $N$Bastão de Retribuição$N$),
  (1987, $N$Bastão de Governo$N$),
  (3700, $N$Bastão da Bênção Sacrificial$N$),
  (3701, $N$Bastão do Domínio Sanguíneo$N$),
  (1989, $N$Bastão de Segurança$N$),
  (3704, $N$Bastão de Caveiras em Enxame$N$),
  (3710, $N$Bastão de Espinhos$N$),
  (3711, $N$Bastão de Navegação Subterrânea$N$),
  (3712, $N$Bastão de Vapor$N$),
  (3713, $N$Bastão Literal$N$),
  (3714, $N$Bastão de Alerta$N$),
  (3705, $N$Bastão do Disciplinador$N$),
  (3707, $N$Bastão do Bobo$N$),
  (3708, $N$Bastão do Marujo$N$),
  (3709, $N$Bastão dos Ermos$N$),
  (3602, $N$Anel da Coragem Surrada$N$),
  (3603, $N$Anel da Bravata$N$),
  (3604, $N$Anel do Aviso do Embusteiro$N$),
  (3607, $N$Anel do Discernimento Dracônico$N$),
  (3617, $N$Anel da Mescla Gigante$N$),
  (3619, $N$Anel do Comando Imperioso$N$),
  (3620, $N$Anel de Armazenar Inspiração$N$),
  (3625, $N$Anel do Conforto da Luz$N$),
  (3628, $N$Anel do Consolo Noturno$N$),
  (3629, $N$Anel de Invocação Poderosa$N$),
  (1929, $N$Anel da Fúria Rubra$N$),
  (3634, $N$Anel da Lembrança$N$),
  (3637, $N$Anel de Selagem$N$),
  (3638, $N$Anel das Sombras$N$),
  (3641, $N$Anel das Pequenas Misericórdias$N$),
  (1953, $N$Anel do Calor$N$),
  (1943, $N$Anel do Imitador$N$),
  (3653, $N$Anel do Sapo$N$),
  (3655, $N$Anel do Guardião do Bosque$N$),
  (3656, $N$Anel do Jarl$N$),
  (3659, $N$Anel do Buscador de Vingança$N$),
  (3660, $N$Anel da Dançarina das Águas$N$),
  (540, $N$Amuleto Comum$N$),
  (542, $N$Amuleto da Aparência$N$),
  (543, $N$Amuleto da Traição$N$),
  (544, $N$Amuleto da Duplicidade$N$),
  (545, $N$Amuleto da Harmonia$N$),
  (546, $N$Amuleto da Saúde$N$),
  (2530, $N$Amuleto da Memória$N$),
  (548, $N$Amuleto à Prova de Detecção e Localização$N$),
  (550, $N$Amuleto de Proteção contra Expulsão$N$),
  (2533, $N$Amuleto de Saúde Sustentável$N$),
  (2538, $N$Amuleto de Redemoinhos$N$),
  (552, $N$Amuleto do Beberrão$N$),
  (2534, $N$Amuleto do Oráculo$N$),
  (554, $N$Amuleto dos Planos$N$),
  (1583, $N$Colar de Adaptação$N$),
  (1585, $N$Colar de Bolas de Fogo$N$),
  (3419, $N$Colar da Fome$N$),
  (1587, $N$Colar de Contas de Oração$N$),
  (556, $N$Escudo Animado$N$),
  (573, $N$Escudo Apara-Flechas$N$),
  (627, $N$Escudo Aríete$N$),
  (699, $N$Escudo Bumerangue$N$),
  (3157, $N$Escudo Agarrador$N$),
  (3162, $N$Escudo de Escamas Verdes$N$),
  (3391, $N$Escudo Espelhado$N$),
  (1878, $N$Escudo de Repulsão$N$),
  (2084, $N$Escudo Sentinela$N$),
  (3797, $N$Escudo +1$N$),
  (3798, $N$Escudo +2$N$),
  (3799, $N$Escudo +3$N$),
  (2102, $N$Escudo da Expressão$N$),
  (2104, $N$Escudo da Visão Distante$N$),
  (3800, $N$Escudo Roedor$N$),
  (2105, $N$Escudo de Atração de Projéteis$N$),
  (3803, $N$Escudo de Reversão de Projéteis$N$),
  (2107, $N$Escudo do Brado$N$),
  (3804, $N$Escudo dos Caídos$N$),
  (2109, $N$Escudo do Cavaleiro$N$),
  (2112, $N$Escudo do Cágado$N$),
  (2198, $N$Escudo Guarda-Magia$N$),
  (2213, $N$Escudo Cravejado$N$),
  (4173, $N$Escudo Zéfiro$N$),
  (1246, $N$Chapéu do Disfarce$N$),
  (3190, $N$Chapéu das Grandes Entradas$N$),
  (1248, $N$Chapéu de Muitas Magias$N$),
  (3191, $N$Chapéu da Acuidade Mental$N$),
  (1249, $N$Chapéu de Pragas$N$),
  (1251, $N$Chapéu de Vórtices$N$),
  (1252, $N$Chapéu de Magia$N$),
  (1262, $N$Elmo da Percepção$N$),
  (1265, $N$Elmo de Compreender Idiomas$N$),
  (1270, $N$Elmo de Telepatia$N$),
  (1272, $N$Elmo de Teleporte$N$),
  (1276, $N$Elmo de Ação Submarina$N$),
  (3213, $N$Elmo da Barbatana Cortante$N$),
  (1012, $N$Elmo Pavoroso$N$),
  (702, $N$Botas de Rastros Falsos$N$),
  (704, $N$Botas de Levitação$N$),
  (2723, $N$Botas do Bote$N$),
  (2724, $N$Botas do Tremor$N$),
  (2725, $N$Botas de Pisada Firme$N$),
  (708, $N$Botas de Passada e Salto$N$),
  (2730, $N$Botas da Avó$N$),
  (2731, $N$Botas do Golpe Veloz$N$),
  (710, $N$Botas do Caminho Sinuoso$N$),
  (711, $N$Botas das Terras Invernais$N$),
  (1174, $N$Manoplas da Fúria Flamejante$N$),
  (1177, $N$Manoplas da Fúria$N$),
  (3104, $N$Manoplas do Verão$N$),
  (1192, $N$Luvas de Aparar Projéteis$N$),
  (1195, $N$Luvas de Natação e Escalada$N$),
  (1197, $N$Luvas de Furto$N$),
  (3138, $N$Luvas do Magíster$N$),
  (3139, $N$Luvas da Sombra Andante$N$),
  (722, $N$Braçadeiras de Arquearia$N$),
  (725, $N$Braçadeiras de Celeridade$N$),
  (726, $N$Braçadeiras de Defesa$N$),
  (2793, $N$Capa de Mira$N$),
  (770, $N$Capa do Charlatão$N$),
  (2841, $N$Manto da Coagulação$N$),
  (2863, $N$Manto das Asas Perversas$N$),
  (2857, $N$Manto do Libertino Discreto$N$),
  (2861, $N$Manto do Rato$N$),
  (2862, $N$Manto do Conjurador de Sombras$N$),
  (1970, $N$Túnica do Verão$N$),
  (2240, $N$Cajado do Poder$N$),
  (2242, $N$Cajado do Domínio$N$),
  (3900, $N$Cajado de Adivinhação$N$),
  (3927, $N$Cajado das Vozes$N$),
  (3897, $N$Cajado de Portais$N$),
  (2231, $N$Cajado do Destino$N$),
  (3895, $N$Cajado de Maldições Menores$N$),
  (2260, $N$Cajado do Definhamento$N$),
  (3921, $N$Cajado do Necromante Branco$N$),
  (3914, $N$Cajado dos Picos$N$),
  (808, $N$Diadema de Explosão$N$),
  (2832, $N$Diadema de Azevinho$N$),
  (2833, $N$Diadema da Persuasão$N$),
  (2834, $N$Diadema do Aprendiz$N$),
  (810, $N$Diadema da Perfeição Humana$N$),
  (2629, $N$Varinha de Freixo$N$),
  (3192, $N$Varinha de Aveleira$N$),
  (2772, $N$Varinha de Bolhas$N$),
  (2791, $N$Varinha de Truques$N$),
  (1108, $N$Varinha de Experimento Fracassado$N$),
  (3001, $N$Bastão Profano$N$),
  (3015, $N$Bastão de Chifre de Alce$N$),
  (3088, $N$Bastão do Corredor Livre$N$),
  (3236, $N$Bastão Uivante$N$),
  (3302, $N$Bastão Para-Raios$N$),
  (3116, $N$Bastão Algoz-de-Carniçal$N$),
  (523, $N$Anel do Aventureiro$N$),
  (2522, $N$Anéis da Aliança$N$),
  (2632, $N$Anel do Assassino$N$),
  (2872, $N$Anel do Trapaceiro Mecânico$N$),
  (3125, $N$Anel de Vidro$N$),
  (3122, $N$Anéis do Glamour$N$),
  (3202, $N$Anel do Teto Celeste$N$),
  (1312, $N$Anel Chifrudo$N$),
  (3282, $N$Anel da Garra do Kraken$N$),
  (834, $N$Amuleto Mecânico$N$),
  (845, $N$Amuleto de Comando$N$),
  (952, $N$Amuleto de Estilhaço Negro$N$),
  (2537, $N$Amuleto do Buquê Agradável$N$),
  (2948, $N$Botas do Desertor$N$),
  (1316, $N$Ferraduras da Velocidade$N$),
  (643, $N$Cinturão da Estirpe Anã$N$),
  (2674, $N$Cinturão dos Ermos$N$),
  (2895, $N$Luvas de Caranguejo$N$),
  (3296, $N$Luvas de Prestidigitação$N$),
  (1453, $N$Luvas Vivas$N$),
  (3076, $N$Luvas de Réplica do Flecheiro$N$),
  (2635, $N$Braçadeiras de Auroque$N$),
  (2763, $N$Braçadeiras de Espinheiro$N$),
  (1328, $N$Braçadeiras do Ilusionista$N$),
  (3096, $N$Braçadeiras Fulminantes$N$),
  (2710, $N$Manto do Salgueiro Azul$N$),
  (2873, $N$Manto da Aranha Mecânica$N$),
  (3129, $N$Manto Planador$N$),
  (3156, $N$Manto Agarrador$N$),
  (2899, $N$Manto Rastejante$N$),
  (2878, $N$Elmo do Comandante$N$),
  (3085, $N$Chapéu do Tolo$N$),
  (3049, $N$Máscara Dentada$N$),
  (3141, $N$Máscara Goblin$N$),
  (2609, $N$Armadura de Amortecimento$N$),
  (2619, $N$Armadura de Salvaguarda$N$),
  (2615, $N$Armadura da Folha$N$),
  (3274, $N$Azagaia de Teleporte$N$),
  (2702, $N$Poção do Elo de Sangue$N$),
  (3160, $N$Poção Maior de Sangue de Troll$N$),
  (2111, $N$Escudo do Dragão Prateado$N$),
  (1268, $N$Elmo da Disjunção$N$),
  (1275, $N$Elmo do Catador$N$),
  (871, $N$Coroa da Floresta$N$),
  -- COM SABOR (in-world witcher-grey)
  (2911, $N$Cajado-de-Cristal$N$),
  (3944, $N$Cajado-de-Pedra$N$),
  (3845, $N$Cajado-Sônico$N$),
  (1047, $N$Cajado-Profano$N$),
  (4037, $N$Cajado-Umbral$N$),
  (3781, $N$Cajado-Serpente$N$),
  (2210, $N$Cajado-Aranha$N$),
  (4140, $N$Cajado-Teia$N$),
  (1412, $N$Cajado-Serpente-de-Jade$N$),
  (3723, $N$Cajado-de-Sorveira$N$),
  (2137, $N$Cajado-Cega-Céu$N$),
  (2404, $N$Cajado-Viajante$N$),
  (3946, $N$Cajado-Deriva-de-Pedra$N$),
  (2258, $N$Cajado-de-Trovão-e-Relâmpago$N$),
  (3892, $N$Cajado-de-Gelo-e-Fogo$N$),
  (3928, $N$Cajado-de-Inverno-e-Gelo$N$),
  (3894, $N$Cajado-da-Meia-Noite$N$),
  (2243, $N$Cajado-Golpeador$N$),
  (2245, $N$Cajado-do-Enxame$N$),
  (3902, $N$Cajado-da-Imundície$N$),
  (3917, $N$Cajado-do-Herdeiro$N$),
  (3909, $N$Cajado-do-Cefalópode$N$),
  (3918, $N$Cajado-da-Árvore-Viva$N$),
  (2250, $N$Cajado-da-Garra-de-Marfim$N$),
  (3910, $N$Cajado-dos-Quatro-Ventos$N$),
  (2255, $N$Cajado-das-Colinas-Enraizadas$N$),
  (3777, $N$Cajado-Feérico$N$),
  (4045, $N$Cajado-Infausto$N$),
  (1289, $N$Cajado-Vai-e-Vem$N$),
  (2753, $N$Cajado-de-Engrenagens-de-Latão$N$),
  (3919, $N$Cajado-do-Não-Nascido$N$),
  (3920, $N$Cajado-Tece-Teia$N$),
  (2247, $N$Cajado-da-Víbora$N$),
  (2253, $N$Cajado-da-Jiboia$N$),
  (2256, $N$Cajado-da-Floresta$N$),
  (3907, $N$Cajado-da-Armada$N$),
  (3908, $N$Cajado-do-Artesão$N$),
  (3888, $N$Cajado-da-Estirpe-Gigante$N$),
  (3889, $N$Cajado-Curva-Gravidade$N$),
  (924, $N$Espada-Curta-do-Penitente$N$),
  (2908, $N$Escudo-do-Penitente$N$),
  (1002, $N$Espada-Longa-Fareja-Dragão$N$),
  (945, $N$Punhal-Vê-às-Cegas$N$),
  (1477, $N$Maça-Esmagadora$N$),
  (1479, $N$Maça-do-Terror$N$),
  (2886, $N$Punhal-Constante$N$),
  (2887, $N$Bastão-Devorador$N$),
  (1194, $N$Luvas-Colhe-Eco$N$),
  (551, $N$Amuleto-Caveira-Negra$N$),
  (1981, $N$Bastão-de-Chama-Corrompida$N$);
DO $$
DECLARE v_n int; v_conv int; v_col int; v_upd int;
BEGIN
  SELECT count(*) INTO v_n FROM _lote;
  SELECT count(*) INTO v_conv FROM ref_itens r JOIN _lote l ON r.id=l.id WHERE r.nome=r.nome_ptbr;
  IF v_conv>0 THEN RAISE EXCEPTION 'PRE: % ja convergidos. Abortado.', v_conv; END IF;
  SELECT count(*) INTO v_col FROM ref_itens r JOIN _lote l ON r.nome=l.novo WHERE r.id<>l.id;
  IF v_col>0 THEN RAISE EXCEPTION 'COLISAO: % nomes ja existem fora do lote. Abortado.', v_col; END IF;
  UPDATE ref_itens r SET nome=l.novo, nome_ptbr=l.novo FROM _lote l WHERE r.id=l.id;
  GET DIAGNOSTICS v_upd=ROW_COUNT;
  IF v_upd <> v_n THEN RAISE EXCEPTION 'POST: mexeu %, esperava %.', v_upd, v_n; END IF;
  RAISE NOTICE 'OK: % convergidos.', v_upd;
END $$;
COMMIT;
