BEGIN;
CREATE TEMP TABLE _lote (id int, novo text) ON COMMIT DROP;
INSERT INTO _lote (id, novo) VALUES
  -- COMMODITY (traducao fiel)
  (2176, $N$Pergaminho de Magia (Nível 1)$N$),
  (2177, $N$Pergaminho de Magia (Nível 2)$N$),
  (2178, $N$Pergaminho de Magia (Nível 3)$N$),
  (2179, $N$Pergaminho de Magia (Nível 4)$N$),
  (2180, $N$Pergaminho de Magia (Nível 5)$N$),
  (2181, $N$Pergaminho de Magia (Nível 6)$N$),
  (2182, $N$Pergaminho de Magia (Nível 7)$N$),
  (2183, $N$Pergaminho de Magia (Nível 8)$N$),
  (2184, $N$Pergaminho de Magia (Nível 9)$N$),
  (2043, $N$Pergaminho de Proteção contra Aberrações$N$),
  (2044, $N$Pergaminho de Proteção contra Bestas$N$),
  (2045, $N$Pergaminho de Proteção contra Celestiais$N$),
  (2046, $N$Pergaminho de Proteção contra Constructos$N$),
  (2047, $N$Pergaminho de Proteção contra Dragões$N$),
  (2048, $N$Pergaminho de Proteção contra Elementais$N$),
  (2049, $N$Pergaminho de Proteção contra Fadas$N$),
  (2050, $N$Pergaminho de Proteção contra Corrompidos$N$),
  (2051, $N$Pergaminho de Proteção contra Gigantes$N$),
  (2052, $N$Pergaminho de Proteção contra Humanoides$N$),
  (2053, $N$Pergaminho de Proteção contra Monstruosidades$N$),
  (2054, $N$Pergaminho de Proteção contra Gosmas$N$),
  (2055, $N$Pergaminho de Proteção contra Plantas$N$),
  (2056, $N$Pergaminho de Proteção contra Mortos-Vivos$N$),
  (3764, $N$Pergaminho de Conjuração$N$),
  (3765, $N$Pergaminho de Fabricação$N$),
  (3766, $N$Pergaminho de Localização de Tesouro$N$),
  (1911, $N$Anel de Salto$N$),
  (1938, $N$Anel de Natação$N$),
  (1956, $N$Anel de Andar sobre Água$N$),
  (1900, $N$Anel de Queda de Pena$N$),
  (1907, $N$Anel de Ação Livre$N$),
  (1898, $N$Anel de Evasão$N$),
  (1915, $N$Anel de Blindagem Mental$N$),
  (1930, $N$Anel de Regeneração$N$),
  (1940, $N$Anel de Telecinese$N$),
  (1959, $N$Anel de Visão de Raio-X$N$),
  (1952, $N$Anel da Verdade$N$),
  (1936, $N$Anel de Reflexão de Magia$N$),
  (1886, $N$Anel de Influência Animal$N$),
  (1944, $N$Anel do Orador$N$),
  (1945, $N$Anel do Aríete$N$),
  (1932, $N$Anel das Estrelas Cadentes$N$),
  (1947, $N$Anel dos Três Desejos$N$),
  (1891, $N$Anel de Invocação de Djinn$N$),
  (1885, $N$Anel da Amizade$N$),
  (1890, $N$Anel de Coleta$N$),
  (1919, $N$Anel de Ofuscação$N$),
  (1926, $N$Anel da Argúcia$N$),
  (1942, $N$Anel da Salvação Temporal$N$),
  (1951, $N$Anel da Traição$N$),
  (3601, $N$Anel de Ajuste Arcano$N$),
  (3614, $N$Anel de Armas Leves$N$),
  (3618, $N$Anel de Vida Acumulada$N$),
  (3647, $N$Anel de Vitalidade Armazenada$N$),
  (3642, $N$Anel de Negação de Magia$N$),
  (3652, $N$Anel do Golfinho$N$),
  (818, $N$Manto Esvoaçante$N$),
  (826, $N$Manto de Muitas Modas$N$),
  (830, $N$Manto do Morcego$N$),
  (832, $N$Manto da Arraia$N$),
  (816, $N$Manto da Aracnídea$N$),
  (2849, $N$Manto de Velas$N$),
  (2846, $N$Manto de Pétalas$N$),
  (2855, $N$Manto da Enguia$N$),
  (2860, $N$Manto do Aríete$N$),
  (2854, $N$Manto do Povo-Urso$N$),
  (2856, $N$Manto do Império$N$),
  (2850, $N$Manto dos Esquilos$N$),
  (2851, $N$Manto de Tentáculos$N$),
  (1963, $N$Túnica dos Olhos$N$),
  (1968, $N$Túnica das Estrelas$N$),
  (1973, $N$Túnica de Itens Úteis$N$),
  (2222, $N$Cajado de Adorno$N$),
  (2224, $N$Cajado de Cantos de Pássaro$N$),
  (2234, $N$Cajado de Flores$N$),
  (3877, $N$Cajado de Canalização$N$),
  (2226, $N$Cajado do Encanto$N$),
  (2228, $N$Cajado de Defesa$N$),
  (3883, $N$Cajado de Penas$N$),
  (3875, $N$Cajado de Atadura$N$),
  (769, $N$Capa de Ampliação$N$),
  (1965, $N$Túnica das Cores Cintilantes$N$),
  (1971, $N$Túnica do Arquimago$N$),
  (1967, $N$Túnica das Serpentes$N$),
  -- COM SABOR (in-world witcher-grey)
  (3463, $N$Martelo-Ósseo$N$),
  (1148, $N$Espada-Curta-Língua-de-Fogo$N$),
  (3097, $N$Azagaia-Vendaval$N$),
  (1414, $N$Azagaia-Relâmpago$N$),
  (760, $N$Maça-Vela$N$),
  (2550, $N$Maça-Ungidora$N$),
  (2371, $N$Tridente-Comanda-Peixe$N$),
  (4044, $N$Punhal-Inquieto$N$),
  (2683, $N$Punhais-Preto-e-Branco$N$),
  (3987, $N$Mangual-dos-Gritos$N$),
  (3924, $N$Cajado-de-Espinhos$N$),
  (3901, $N$Cajado-de-Esporos$N$),
  (3880, $N$Cajado-da-Desolação$N$),
  (3881, $N$Cajado-Dissolvente$N$),
  (3873, $N$Cajado-Estilhaço$N$),
  (3199, $N$Punhal-Despedaça-Peito$N$);
DO $$
DECLARE v_n int; v_conv int; v_col int; v_upd int;
BEGIN
  SELECT count(*) INTO v_n FROM _lote;
  SELECT count(*) INTO v_conv FROM ref_itens r JOIN _lote l ON r.id=l.id WHERE r.nome=r.nome_ptbr;
  IF v_conv>0 THEN RAISE EXCEPTION 'PRE: % ja convergidos. Abortado.', v_conv; END IF;
  SELECT count(*) INTO v_col FROM ref_itens r JOIN _lote l ON r.nome=l.novo WHERE r.id<>l.id;
  IF v_col>0 THEN RAISE EXCEPTION 'COLISAO: % nomes ja existem fora do lote. Abortado.', v_col; END IF;
  UPDATE ref_itens r SET nome=l.novo, nome_ptbr=l.novo FROM _lote l WHERE r.id=l.id;
  GET DIAGNOSTICS v_upd=ROW_COUNT;
  IF v_upd <> v_n THEN RAISE EXCEPTION 'POST: mexeu %, esperava %.', v_upd, v_n; END IF;
  RAISE NOTICE 'OK: % convergidos.', v_upd;
END $$;
COMMIT;
