BEGIN;
CREATE TEMP TABLE _lote (id int, novo text) ON COMMIT DROP;
INSERT INTO _lote (id, novo) VALUES
  -- COMMODITY (traducao fiel)
  (1720, $N$Poção de Forma Aquosa$N$),
  (3519, $N$Poção de Gosto Ruim$N$),
  (3520, $N$Poção de Ricochete$N$),
  (3521, $N$Poção de Flutuação$N$),
  (1723, $N$Poção de Escalada$N$),
  (1725, $N$Poção de Força do Gigante das Nuvens$N$),
  (1729, $N$Poção de Compreensão$N$),
  (3528, $N$Poção de Purificação Severa$N$),
  (1733, $N$Poção da Majestade Dracônica$N$),
  (3529, $N$Poção de Força Minguante$N$),
  (3530, $N$Poção de Refulgência$N$),
  (3531, $N$Poção da Verdade Fortalecedora$N$),
  (1734, $N$Poção de Sopro de Fogo$N$),
  (1736, $N$Poção de Força do Gigante do Fogo$N$),
  (3534, $N$Poção de Névoa Congelante$N$),
  (1744, $N$Poção de Força do Gigante do Gelo$N$),
  (1748, $N$Poção de Tamanho Gigante$N$),
  (3537, $N$Poção de Força de Gigante$N$),
  (1751, $N$Poção de Invisibilidade Maior$N$),
  (3545, $N$Poção de Possibilidades Infinitas$N$),
  (1766, $N$Poção de Longevidade$N$),
  (3548, $N$Poção de Maleabilidade$N$),
  (1768, $N$Poção de Poder Máximo$N$),
  (1769, $N$Poção de Controle Mental (besta)$N$),
  (1770, $N$Poção de Controle Mental (humanoide)$N$),
  (1771, $N$Poção de Controle Mental (monstro)$N$),
  (1776, $N$Poção de Veneno$N$),
  (1780, $N$Poção de Policromia$N$),
  (1781, $N$Poção de Possibilidade$N$),
  (1782, $N$Poção de Fortitude Psiônica$N$),
  (1785, $N$Poção de Pugilismo$N$),
  (3555, $N$Poção de Forma de Areia$N$),
  (3556, $N$Poção de Patinação$N$),
  (1790, $N$Poção de Força do Gigante de Pedra$N$),
  (1792, $N$Poção de Força do Gigante da Tempestade$N$),
  (1794, $N$Poção de Cura Superior$N$),
  (3559, $N$Poção de Transparência$N$),
  (1802, $N$Poção de Descanso Vigilante$N$),
  (3562, $N$Poção de Forma de Worg$N$),
  (2612, $N$Armadura de Resistência$N$),
  (1882, $N$Anel de Resistência ao Ácido$N$),
  (1903, $N$Anel de Resistência ao Fogo$N$),
  (1905, $N$Anel de Resistência à Força$N$),
  (1913, $N$Anel de Resistência a Relâmpagos$N$),
  (1917, $N$Anel de Resistência ao Necrótico$N$),
  (1920, $N$Anel de Resistência a Veneno$N$),
  (1924, $N$Anel de Resistência ao Psíquico$N$),
  (1927, $N$Anel de Resistência ao Radiante$N$),
  (1949, $N$Anel de Resistência ao Trovão$N$),
  (641, $N$Cinturão da Força do Gigante das Nuvens$N$),
  (645, $N$Cinturão da Força do Gigante do Fogo$N$),
  (647, $N$Cinturão da Força do Gigante do Gelo$N$),
  (649, $N$Cinturão da Força do Gigante das Colinas$N$),
  (651, $N$Cinturão da Força do Gigante de Pedra$N$),
  (653, $N$Cinturão da Força do Gigante da Tempestade$N$),
  (659, $N$Máscara de Dragão Negro$N$),
  (684, $N$Máscara de Dragão Azul$N$),
  (1218, $N$Máscara de Dragão Verde$N$),
  (1868, $N$Máscara de Dragão Vermelho$N$),
  (2469, $N$Máscara de Dragão Branco$N$),
  (1513, $N$Máscara da Rainha Dragão$N$),
  (475, $N$+1 Amuleto do Devoto$N$),
  (489, $N$+2 Amuleto do Devoto$N$),
  (503, $N$+3 Amuleto do Devoto$N$),
  (478, $N$+1 Cinturão de Couro de Dragão$N$),
  (492, $N$+2 Cinturão de Couro de Dragão$N$),
  (506, $N$+3 Cinturão de Couro de Dragão$N$),
  (482, $N$+1 Bastão do Guardião do Pacto$N$),
  (496, $N$+2 Bastão do Guardião do Pacto$N$),
  (510, $N$+3 Bastão do Guardião do Pacto$N$),
  (484, $N$+1 Varinha do Mago de Guerra$N$),
  (498, $N$+2 Varinha do Mago de Guerra$N$),
  (512, $N$+3 Varinha do Mago de Guerra$N$),
  (3858, $N$Pergaminho de Magia$N$),
  (2185, $N$Pergaminho de Magia (Truque)$N$),
  (2065, $N$Pergaminho de Invocação de Tarrasque$N$),
  (2066, $N$Pergaminho do Cometa$N$),
  (2067, $N$Pergaminho de Invocação de Titã (Senhor Animal)$N$),
  (2068, $N$Pergaminho de Invocação de Titã (Gosma da Aniquilação)$N$),
  (2069, $N$Pergaminho de Invocação de Titã (Colosso)$N$),
  (2070, $N$Pergaminho de Invocação de Titã (Cataclismo Elemental)$N$),
  (2071, $N$Pergaminho de Invocação de Titã (Empíreo)$N$),
  (2072, $N$Pergaminho de Invocação de Titã (Kraken)$N$),
  (2073, $N$Pergaminho de Invocação de Titã (Tarrasque)$N$),
  -- COM SABOR (in-world witcher-grey)
  (1011, $N$Punhal-Dente-de-Dragão$N$),
  (3077, $N$Punhal-Lampejo$N$),
  (680, $N$Lança-de-Sangue$N$),
  (2699, $N$Lança-Bebe-Sangue$N$),
  (3485, $N$Lança-Pestilenta$N$),
  (3140, $N$Lança-Roedora$N$),
  (2712, $N$Maça-Quebra-Osso$N$),
  (1001, $N$Espada-Longa-Dracônica$N$),
  (3970, $N$Espada-Chaga$N$),
  (3967, $N$Espada-da-Serpente$N$),
  (2347, $N$Tridente-Convoca-Maré$N$),
  (4025, $N$Tridente-do-Vórtice$N$),
  (2232, $N$Cajado-de-Brasa$N$),
  (2288, $N$Cajado-Solar$N$),
  (2164, $N$Lança-Traiçoeira$N$),
  (1413, $N$Azagaia-Traiçoeira$N$);
DO $$
DECLARE v_n int; v_conv int; v_col int; v_upd int;
BEGIN
  SELECT count(*) INTO v_n FROM _lote;
  SELECT count(*) INTO v_conv FROM ref_itens r JOIN _lote l ON r.id=l.id WHERE r.nome=r.nome_ptbr;
  IF v_conv>0 THEN RAISE EXCEPTION 'PRE: % ja convergidos. Abortado.', v_conv; END IF;
  SELECT count(*) INTO v_col FROM ref_itens r JOIN _lote l ON r.nome=l.novo WHERE r.id<>l.id;
  IF v_col>0 THEN RAISE EXCEPTION 'COLISAO: % nomes ja existem fora do lote. Abortado.', v_col; END IF;
  UPDATE ref_itens r SET nome=l.novo, nome_ptbr=l.novo FROM _lote l WHERE r.id=l.id;
  GET DIAGNOSTICS v_upd=ROW_COUNT;
  IF v_upd <> v_n THEN RAISE EXCEPTION 'POST: mexeu %, esperava %.', v_upd, v_n; END IF;
  RAISE NOTICE 'OK: % convergidos.', v_upd;
END $$;
COMMIT;
