BEGIN;
CREATE TEMP TABLE _lote (id int, novo text) ON COMMIT DROP;
INSERT INTO _lote (id, novo) VALUES
  -- CONVERGENCIA (nome PT ja curado)
  (999, $N$Adaga-do-Rio$N$),
  (3461, $N$Agenda-Animada$N$),
  (599, $N$Alforje-do-Cru$N$),
  (3579, $N$Bomba-Radiante$N$),
  (3592, $N$Bracelete-Resoluto$N$),
  (3513, $N$Caixa-Retratista$N$),
  (615, $N$Caixa-Sentinela$N$),
  (3805, $N$Camisa-Mutante$N$),
  (3577, $N$Cobertor-Ponte$N$),
  (851, $N$Concertina-de-Gelo$N$),
  (852, $N$Concha-Abrigo$N$),
  (943, $N$Cubo-Fortaleza$N$),
  (937, $N$Cubo-Portal$N$),
  (3475, $N$Disfarce-Perfeito$N$),
  (3487, $N$Espelho-Dimensional$N$),
  (3787, $N$Estatueta-Servil$N$),
  (3760, $N$Fragmento-Proibido$N$),
  (716, $N$Garrafa-Sem-Fundo$N$),
  (3587, $N$Livro-Registrador$N$),
  (1496, $N$Manual-de-Construto de Argila$N$),
  (1498, $N$Manual-de-Construto de Carne$N$),
  (1502, $N$Manual-de-Construto de Ferro$N$),
  (1506, $N$Manual-de-Construto de Pedra$N$),
  (3590, $N$Moldura-Rearmadora$N$),
  (994, $N$Orbe-Conselheira$N$),
  (3460, $N$Orbe-Quebradora$N$),
  (3452, $N$Opus-Maleficarum$N$),
  (3821, $N$Pedra-Saltitante$N$),
  (3576, $N$Pena-Escriba$N$),
  (3476, $N$Perfume-Purificador$N$),
  (3593, $N$Pomada-Restauradora$N$),
  (3504, $N$Prumo-Elemental$N$),
  (1105, $N$Rasga-Olhos$N$),
  (3817, $N$Remo-Prateado$N$),
  (3574, $N$Remo-Veloz$N$),
  (3780, $N$Retrato-Sentinela$N$),
  (856, $N$Retrato-que-Fala$N$),
  (683, $N$Rosa-Cristalina Azul$N$),
  (657, $N$Rosa-Cristalina Negra$N$),
  (1216, $N$Rosa-Cristalina Verde$N$),
  (663, $N$Seiva-Negra$N$),
  (1096, $N$Semente Explosiva$N$),
  (3468, $N$Sombrinha-Temperada$N$),
  (847, $N$Tecido-Espelho$N$),
  (743, $N$Vassoura-Andarilha$N$),
  (985, $N$Algemas Dimensionais$N$),
  (968, $N$Baralho Selvagem$N$),
  (1068, $N$Berloque Naturalista$N$),
  (1065, $N$Berloque Silvestre$N$),
  (721, $N$Braçal-das-Lâminas$N$),
  (781, $N$Carruagem$N$),
  (237, $N$Corrente de Ferro$N$),
  (71, $N$Couro Curtido Material$N$),
  (1369, $N$Cristal-Orbital da Fortitude$N$),
  (246, $N$Cristal-Pulso Bruto$N$),
  (564, $N$Cristal-Reserva$N$),
  (1126, $N$Estatueta Dourada (felinos)$N$),
  (1122, $N$Estatueta de Bronze (predador alado)$N$),
  (757, $N$Estrepes de Ferro (saco de 20)$N$),
  (1113, $N$Fala-Longe$N$),
  (1048, $N$Fragmento de Essência Elemental$N$),
  (1053, $N$Gema Elemental (ar)$N$),
  (1057, $N$Gema Elemental (fogo)$N$),
  (1059, $N$Gema Elemental (terra)$N$),
  (1055, $N$Gema Elemental (água)$N$),
  (991, $N$Kit de Disfarce$N$),
  (747, $N$Lanterna Direcional$N$),
  (692, $N$Livro Encadernado$N$),
  (941, $N$Manto de Cultista$N$),
  (99, $N$Mochila de Couro Curtido$N$),
  (980, $N$Máscara-de-Sombra$N$),
  (100, $N$Odre de Bexiga$N$),
  (3506, $N$Oásis-de-Bolso$N$),
  (846, $N$Roupas Comuns$N$),
  (1141, $N$Roupas Finas$N$),
  (777, $N$Tapete Rasteiro (grande)$N$),
  (779, $N$Tapete Rasteiro (monumental)$N$),
  (775, $N$Tapete Rasteiro (médio)$N$),
  (773, $N$Tapete Rasteiro (pequeno)$N$),
  (848, $N$Vinho Comum$N$),
  -- COMMODITY (traducao fiel)
  (568, $N$Armadura da Invulnerabilidade$N$),
  (2614, $N$Armadura do Despeito$N$),
  (2617, $N$Armadura da Vulnerabilidade$N$),
  (570, $N$Armadura da Vulnerabilidade (Concussão)$N$),
  (571, $N$Armadura da Vulnerabilidade (Perfuração)$N$),
  (572, $N$Armadura da Vulnerabilidade (Corte)$N$),
  (2616, $N$Armadura do Ngobou$N$),
  (3393, $N$Armadura de Mithral$N$),
  (3362, $N$Máscara do Anonimato$N$),
  (1511, $N$Máscara de Aparência Alterada$N$),
  (3363, $N$Máscara da Fúria Implacável$N$),
  (1512, $N$Máscara da Fera$N$),
  (3364, $N$Máscara da Gazela Saltadora$N$),
  (3365, $N$Máscara do Chefe de Guerra$N$),
  (3366, $N$Máscara do Veado Branco$N$),
  (3370, $N$Máscara do Caos$N$),
  (3501, $N$Máscara de Médico da Peste$N$),
  (3052, $N$Máscara Devora-Medo$N$),
  (3075, $N$Máscara Renegada-da-Carne$N$),
  (3654, $N$Anel do Cavaleiro do Gelo$N$),
  (1417, $N$Máscara do Bobo$N$),
  (3277, $N$Máscara do Justiceiro$N$),
  (1660, $N$Máscara do Falcão-Peregrino$N$),
  (3450, $N$Máscara de Oni$N$),
  (2135, $N$Elmo de Caveira$N$),
  (3792, $N$Coroa de Dente de Tubarão$N$),
  (3325, $N$Coroa Lupina$N$),
  (3268, $N$Coroa de Hera da Profecia$N$),
  (1552, $N$Coroa Guarda-Mente$N$),
  (873, $N$Coroa de Cometas Rodopiantes$N$),
  (872, $N$Coroa do Portador da Ira$N$),
  (1158, $N$Elmo da Cidadela Voadora$N$),
  (1824, $N$Elmo de Hélice$N$),
  (2449, $N$Elmo Vigilante$N$),
  (4047, $N$Cartola Útil$N$),
  (1109, $N$Elmo da Teimosia$N$),
  (2200, $N$Elmo de Navegação Arcana$N$),
  (1686, $N$Piwafwi (Manto Élfico)$N$),
  (3588, $N$Manto Vermelho de Montaria$N$),
  (3957, $N$Manto do Sobrevivente$N$),
  (4019, $N$Manto Transformante$N$),
  (4068, $N$Manto de Pele-do-Vazio$N$),
  (4147, $N$Manto Sussurrante$N$),
  (2483, $N$Asas de Voo$N$),
  (3739, $N$Sandálias do Andarilho do Deserto$N$),
  (3742, $N$Botas de Sátiro$N$),
  (3995, $N$Botas de Três Seções$N$),
  (2454, $N$Botas do Viajante$N$),
  (4155, $N$Botas Anda-Vento$N$),
  (2481, $N$Botas Aladas$N$),
  (3433, $N$Braçadeiras de Polvo$N$),
  (3466, $N$Manoplas Pareadas de Golpe$N$),
  (3580, $N$Braçadeiras Radiantes$N$),
  (3782, $N$Braçadeiras Serpentinas$N$),
  (3945, $N$Manoplas Mastiga-Pedra$N$),
  (3951, $N$Luvas do Mago Discreto$N$),
  (3996, $N$Manoplas do Estrangulador$N$),
  (4029, $N$Luvas do Peso Verdadeiro$N$),
  (2496, $N$Manoplas Ceifa-Dragão$N$),
  (3779, $N$Luvas do Senescal$N$),
  (3051, $N$Anel do Sondador$N$),
  (3725, $N$Anel do Arruaceiro$N$),
  (3806, $N$Anel Cintilante$N$),
  (3812, $N$Anéis de Sinal$N$),
  (2120, $N$Anel de Sinete$N$),
  (3828, $N$Anel de Luz-Ardósia$N$),
  (2196, $N$Anel de Reabastecer Magia$N$),
  (2326, $N$Anel Teleportador$N$),
  (4039, $N$Vara de Radiestesia Infalível$N$),
  (3586, $N$Escudo Recôndito$N$),
  (4167, $N$Anel Morde-Lobo$N$),
  (4175, $N$Anel Tirolesa$N$),
  (1894, $N$Anel de Comando Elemental (Ar)$N$),
  (1895, $N$Anel de Comando Elemental (Terra)$N$),
  (1896, $N$Anel de Comando Elemental (Fogo)$N$),
  (1897, $N$Anel de Comando Elemental (Água)$N$),
  (3608, $N$Anel de Comando Elemental$N$),
  (740, $N$Broche de Proteção$N$),
  (2030, $N$Amuleto do Santuário$N$),
  (2033, $N$Escaravelho de Proteção$N$),
  (3464, $N$Amuleto Ouroboros$N$),
  (1819, $N$Amuleto Primal$N$),
  (1516, $N$Amuleto do Mestre$N$),
  (2101, $N$Amuleto do Guardião-Escudo$N$),
  (3768, $N$Amuleto da Bruxa do Mar$N$),
  (4168, $N$Amuleto do Lenho-Anil$N$),
  (4174, $N$Amuleto do Olho Zífio$N$),
  (3429, $N$Varinha de Carvalho$N$),
  (4020, $N$Varinha Transformante$N$),
  (1852, $N$Bordão do Acrobata$N$),
  (3911, $N$Cajado do Porta-Lanterna$N$),
  (1072, $N$Cajado Enfeitiçado (Truque)$N$),
  (1073, $N$Cajado Enfeitiçado (Nível 1)$N$),
  (1074, $N$Cajado Enfeitiçado (Nível 2)$N$),
  (1075, $N$Cajado Enfeitiçado (Nível 3)$N$),
  (1076, $N$Cajado Enfeitiçado (Nível 4)$N$),
  (1077, $N$Cajado Enfeitiçado (Nível 5)$N$),
  (1078, $N$Cajado Enfeitiçado (Nível 6)$N$),
  (1079, $N$Cajado Enfeitiçado (Nível 7)$N$),
  (1080, $N$Cajado Enfeitiçado (Nível 8)$N$),
  (946, $N$Punhal dos Solos de Guitarra$N$),
  (1421, $N$Punhal +1 Vagabundo$N$),
  (1645, $N$Arco Longo Descomunal$N$),
  (1462, $N$Arco Longo do Lar Curativo$N$),
  (3851, $N$Lança do Norte$N$),
  (3852, $N$Lança do Coração Silenciado$N$),
  (3853, $N$Lança da Baleia Ocidental$N$),
  (4026, $N$Tridente da Maré Anelante$N$),
  (3796, $N$Mangual do Pastor$N$),
  (2869, $N$Maça Mecânica da Divindade$N$),
  (3142, $N$Escudo Goblin$N$),
  (2008, $N$Escudo de Ruídio$N$),
  (1654, $N$Escudo do Pária$N$),
  (2108, $N$Escudo do Couraçado Flamejante$N$),
  (3954, $N$Poção Superior de Sangue de Troll$N$),
  (3955, $N$Poção Suprema de Sangue de Troll$N$),
  (2798, $N$Tapete Voador$N$),
  (1636, $N$Ornitóptero Voador$N$),
  (3170, $N$Pente de Cabelo de Proteção$N$),
  (3182, $N$Aljava de Pergaminhos Prática$N$),
  (3949, $N$Tubo de Pergaminho Resistente$N$),
  (3767, $N$Pergaminhos de Correspondência$N$),
  (3127, $N$Óculos de Rodentius$N$),
  (2444, $N$Bainha de Varinha$N$),
  (1962, $N$Túnica$N$),
  (1975, $N$Túnicas$N$),
  -- COM SABOR (in-world)
  (1261, $N$Manto do Mastim-Brasa$N$),
  (3854, $N$Couraça-Morde-Lança$N$),
  (2329, $N$Bastão-Tentáculo$N$),
  (3264, $N$Maça-Inimiga-do-Ferro$N$),
  (3962, $N$Espada-dos-Santos-Tombados$N$),
  (1469, $N$Tarokka-dos-Ecos$N$);
DO $$
DECLARE v_n int; v_conv int; v_col int; v_upd int;
BEGIN
  SELECT count(*) INTO v_n FROM _lote;
  SELECT count(*) INTO v_conv FROM ref_itens r JOIN _lote l ON r.id=l.id WHERE r.nome=r.nome_ptbr;
  IF v_conv>0 THEN RAISE EXCEPTION 'PRE: % ja convergidos. Abortado.', v_conv; END IF;
  SELECT count(*) INTO v_col FROM ref_itens r JOIN _lote l ON r.nome=l.novo WHERE r.id<>l.id;
  IF v_col>0 THEN RAISE EXCEPTION 'COLISAO: % nomes ja existem fora do lote. Abortado.', v_col; END IF;
  UPDATE ref_itens r SET nome=l.novo, nome_ptbr=l.novo FROM _lote l WHERE r.id=l.id;
  GET DIAGNOSTICS v_upd=ROW_COUNT;
  IF v_upd <> v_n THEN RAISE EXCEPTION 'POST: mexeu %, esperava %.', v_upd, v_n; END IF;
  RAISE NOTICE 'OK: % convergidos.', v_upd;
END $$;
COMMIT;
